-- Here you can edit the behavior of the game!
-- Use these default settings as references.
OBSTACLE_MAX_SPEED = 8
OBSTACLE_MIN_SPEED = 2
OBSTACLE_MAX_SIZE = 2
OBSTACLE_MIN_SIZE = 1
OBSTACLE_MAX_DIRECTION_SPEED = 4
OBSTACLE_MIN_DIRECTION_SPEED = 2
OBSTACLE_ROTATION_SPEED = 0.05
OBSTACLE_SCALE_FACTOR = 0.15

OBSTACLES_COUNT_HARD = 55
OBSTACLES_COUNT_NORMAL = 40
OBSTACLES_COUNT_EASY = 25

BACKGROUND_SPEED_IDLE = 200
BACKGROUND_SPEED = 400

PLAYER_MOVE_SPEED = 350
PLAYER_GRAVITY = 2
PLAYER_SCALE_FACTOR = 0.5

FULLSCREEN = true
MUSIC_VOLUME = 0.70 -- Between 0.0 and 1.0

-- GAME MENU OPTIONS
PLAY_MUSIC = true
DIFFICULTY = "NORMAL"
