-- Here you can edit the behavior of the game!
-- Use these default settings as references.
OBSTACLE_MAX_SPEED = 8
OBSTACLE_MIN_SPEED = 2
OBSTACLE_MAX_SIZE = 2
OBSTACLE_MIN_SIZE = 1
OBSTACLE_MAX_DIRECTION_SPEED = 4
OBSTACLE_MIN_DIRECTION_SPEED = 2
OBSTACLE_ROTATION_SPEED = 0.05

OBSTACLES_COUNT_HARD = 26
OBSTACLES_COUNT_NORMAL = 18
OBSTACLES_COUNT_EASY = 10

BACKGROUND_SPEED_IDLE = 350
BACKGROUND_SPEED = 450
PLAYER_MOVE_SPEED = 350
PLAYER_GRAVITY = 4
MUSIC_VOLUME = 0.70 -- Between 0.0 and 1.0
PLAYER_SCALE_FACTOR = 0.5
OBSTACLE_SCALE_FACTOR = 0.125
FULLSCREEN = true

-- GAME MENU OPTIONS
PLAY_MUSIC = true
DIFFICULTY = "NORMAL"
